import Head from "next/head";
import Header from "@/components/layout/Header";
import Main from "@/components/layout/Main";
// import Footer from "@/components/layout/Footer";


export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <Header />
      <Main/>
      {/* <Footer/> */}
    </>
  )
}
